services:
  - type: web
    name: psybot-backend
    env: python
    region: frankfurt  # Ou change selon ta localisation
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: HF_TOKEN
        sync: false
